name: WebdriverIO Tests

on:
  push:
    branches:
      - krishna/wip

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Allure CLI and generate report
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
        tar -zxvf allure-2.25.0.tgz
        export PATH=$PATH:$(pwd)/allure-2.25.0/bin
        allure generate --clean ./allure-results

    - name: Archive Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report