name: WebdriverIO Tests

on:
  push:
    branches:
      - krishna/wip

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Allure CLI (npm)
      run: npm install -g allure-commandline
    
    - name: Run tests
      run: npm run bs

    - name: Generate Allure report
      run: allure generate --clean ./allure-results

    - name: Archive Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
