name: WebdriverIO Tests

on:
  # schedule:
  #   - cron: '0 */3 * * *'
  push:
    branches:
      - krishna/wip
      - main
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

  test:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.result == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run tests
      run: npm run bs

    - name: Archive Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./allure-results
